[package]
name = "rust-api"
version = "0.1.0"
authors = ["NinthAutumn <arif.iwamoto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
listenfd = "0.3"
dotenv="0.15.0"